// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2x3LxlGk2qbTs6qXAYr2bd_K9BpO3DaQ',
    appId: '1:159293961717:android:66852543aec2d9c1741cbc',
    messagingSenderId: '159293961717',
    projectId: 'anantkaal-demo-f998b',
    storageBucket: 'anantkaal-demo-f998b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeJqfvnJlQK5DvCchLcWs17FK4NnwiIzA',
    appId: '1:159293961717:ios:90ad246186b8aab9741cbc',
    messagingSenderId: '159293961717',
    projectId: 'anantkaal-demo-f998b',
    storageBucket: 'anantkaal-demo-f998b.firebasestorage.app',
    androidClientId: '159293961717-vpqgenja4bt67firgedobglrsa2uo8v1.apps.googleusercontent.com',
    iosClientId: '159293961717-1s5cilt0vqdr5agicljc3igskl8b7u0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.anantkaalassignment',
  );

}